### PR TITLE
Draft: Refresh token

### PR DESCRIPTION
**Pull request by mariana0412**
This PR introduces the basic functionality for token refreshing using the TokenRefreshService which will work is the app is active. The service utilizes a timer to automatically refresh the token when it's going to be expired.

- startTokenRefresh is called when the user logs in to start the token refresh process based on the token's expiration datetime
- stopTokenRefresh is called when the user logs out to stop the timer

### CODE REVIEW

**Comment by mariana0412** [comment]
Similar issue https://forums.developer.apple.com/forums/thread/767446 and response https://developer.apple.com/forums/thread/685525

**Comment by himanshunaidu** [comment]
Got it! Thanks for all this.
This is incredibly informative. So based on the second link, it's doubtful that our use case is fulfilled.

**Comment by himanshunaidu** [comment]
One question, since I haven't looked very deeply into the functionality of DispatchSource, but the DispatchSource.makeTimerSource function, would it stop running once the app loses focus (like is sent to the background)?

**Comment by himanshunaidu** [comment]
Since the token lifetime is 24 hours, we could use a much simpler logic of refreshing token every time the user lands on the home page. This would seem reasonable

**Review by himanshunaidu — APPROVED** [review]

**Comment by himanshunaidu** [comment]
Looks great! Thank you for your patience.
I'll merge this now itself, so that we can focus on the API transmission

**Pull request merged**
